// Registry der EN-16931-Feldbezeichnungen: Business Terms (BT-…) und
// Business Groups (BG-…) mit deutschen Namen, wie sie auch die
// XRechnung-Spezifikation verwendet. Quelle: Semantisches Datenmodell
// EN 16931-1 (deutsche Benennungen der KoSIT-Übersetzung).
//
// Hinweis zur Nummerierung: BT-4 wurde im Normungsprozess gestrichen und
// existiert nicht; BT-162…BT-165 sind die späteren Zusatzzeilen der
// vier Anschriften.
import Foundation

public enum EN16931 {

    /// Deutscher Name eines Business Terms / einer Business Group.
    public static func name(for term: String) -> String? {
        names[term]
    }

    static let names: [String: String] = [
        // --- Business Groups
        "BG-1": "Rechnungsanmerkung",
        "BG-2": "Prozesssteuerung",
        "BG-3": "Referenz auf die vorausgegangene Rechnung",
        "BG-4": "Verkäufer",
        "BG-5": "Postanschrift des Verkäufers",
        "BG-6": "Kontaktdaten des Verkäufers",
        "BG-7": "Käufer (Erwerber)",
        "BG-8": "Postanschrift des Käufers",
        "BG-9": "Kontaktdaten des Käufers",
        "BG-10": "Zahlungsempfänger",
        "BG-11": "Steuerbevollmächtigter des Verkäufers",
        "BG-12": "Postanschrift des Steuerbevollmächtigten",
        "BG-13": "Lieferinformationen",
        "BG-14": "Rechnungszeitraum",
        "BG-15": "Lieferanschrift",
        "BG-16": "Zahlungsanweisungen",
        "BG-17": "Überweisung",
        "BG-18": "Zahlungskarteninformationen",
        "BG-19": "Lastschrift",
        "BG-20": "Nachlass auf Dokumentenebene",
        "BG-21": "Zuschlag auf Dokumentenebene",
        "BG-22": "Gesamtsummen auf Dokumentenebene",
        "BG-23": "Umsatzsteueraufschlüsselung",
        "BG-24": "Rechnungsbegründende Unterlage",
        "BG-25": "Rechnungsposition",
        "BG-26": "Rechnungszeitraum der Position",
        "BG-27": "Nachlass auf Positionsebene",
        "BG-28": "Zuschlag auf Positionsebene",
        "BG-29": "Preiseinzelheiten",
        "BG-30": "Umsatzsteuerinformationen der Position",
        "BG-31": "Artikelinformationen",
        "BG-32": "Artikelattribut",

        // --- Dokument-Kopf
        "BT-1": "Rechnungsnummer",
        "BT-2": "Rechnungsdatum",
        "BT-3": "Code für den Rechnungstyp",
        "BT-5": "Code für die Rechnungswährung",
        "BT-6": "Code für die Umsatzsteuer-Abrechnungswährung",
        "BT-7": "Datum der Steuerfälligkeit",
        "BT-8": "Code für das Datum der Steuerfälligkeit",
        "BT-9": "Fälligkeitsdatum der Zahlung",
        "BT-10": "Käuferreferenz (z.B. Leitweg-ID)",
        "BT-11": "Projektreferenz",
        "BT-12": "Vertragsreferenz",
        "BT-13": "Bestellreferenz",
        "BT-14": "Auftragsreferenz (Verkäufer)",
        "BT-15": "Referenz auf die Empfangsbestätigung",
        "BT-16": "Referenz auf den Lieferschein (Versandanzeige)",
        "BT-17": "Referenz auf Ausschreibung oder Los",
        "BT-18": "Kennung des Rechnungsgegenstands",
        "BT-19": "Buchungsreferenz des Käufers",
        "BT-20": "Zahlungsbedingungen",
        "BT-21": "Code der Anmerkungsart",
        "BT-22": "Anmerkung zur Rechnung",
        "BT-23": "Geschäftsprozesstyp",
        "BT-24": "Spezifikationskennung (Profil)",
        "BT-25": "Nummer der vorausgegangenen Rechnung",
        "BT-26": "Datum der vorausgegangenen Rechnung",

        // --- Verkäufer
        "BT-27": "Name des Verkäufers",
        "BT-28": "Handelsname des Verkäufers",
        "BT-29": "Kennung des Verkäufers",
        "BT-30": "Rechtliche Registrierungskennung des Verkäufers",
        "BT-31": "Umsatzsteuer-Identifikationsnummer des Verkäufers",
        "BT-32": "Steuerregistrierungskennung des Verkäufers (z.B. Steuernummer)",
        "BT-33": "Weitere rechtliche Informationen des Verkäufers",
        "BT-34": "Elektronische Adresse des Verkäufers",
        "BT-35": "Verkäuferanschrift, Zeile 1",
        "BT-36": "Verkäuferanschrift, Zeile 2",
        "BT-37": "Ort der Verkäuferanschrift",
        "BT-38": "Postleitzahl der Verkäuferanschrift",
        "BT-39": "Region/Bundesland der Verkäuferanschrift",
        "BT-40": "Ländercode der Verkäuferanschrift",
        "BT-41": "Kontaktstelle des Verkäufers",
        "BT-42": "Telefonnummer des Verkäuferkontakts",
        "BT-43": "E-Mail-Adresse des Verkäuferkontakts",

        // --- Käufer
        "BT-44": "Name des Käufers",
        "BT-45": "Handelsname des Käufers",
        "BT-46": "Kennung des Käufers",
        "BT-47": "Rechtliche Registrierungskennung des Käufers",
        "BT-48": "Umsatzsteuer-Identifikationsnummer des Käufers",
        "BT-49": "Elektronische Adresse des Käufers",
        "BT-50": "Käuferanschrift, Zeile 1",
        "BT-51": "Käuferanschrift, Zeile 2",
        "BT-52": "Ort der Käuferanschrift",
        "BT-53": "Postleitzahl der Käuferanschrift",
        "BT-54": "Region/Bundesland der Käuferanschrift",
        "BT-55": "Ländercode der Käuferanschrift",
        "BT-56": "Kontaktstelle des Käufers",
        "BT-57": "Telefonnummer des Käuferkontakts",
        "BT-58": "E-Mail-Adresse des Käuferkontakts",

        // --- Zahlungsempfänger und Steuerbevollmächtigter
        "BT-59": "Name des Zahlungsempfängers",
        "BT-60": "Kennung des Zahlungsempfängers",
        "BT-61": "Rechtliche Registrierungskennung des Zahlungsempfängers",
        "BT-62": "Name des Steuerbevollmächtigten des Verkäufers",
        "BT-63": "Umsatzsteuer-Identifikationsnummer des Steuerbevollmächtigten",
        "BT-64": "Anschrift des Steuerbevollmächtigten, Zeile 1",
        "BT-65": "Anschrift des Steuerbevollmächtigten, Zeile 2",
        "BT-66": "Ort der Anschrift des Steuerbevollmächtigten",
        "BT-67": "Postleitzahl der Anschrift des Steuerbevollmächtigten",
        "BT-68": "Region/Bundesland der Anschrift des Steuerbevollmächtigten",
        "BT-69": "Ländercode der Anschrift des Steuerbevollmächtigten",

        // --- Lieferung
        "BT-70": "Name des Waren-/Dienstleistungsempfängers",
        "BT-71": "Kennung des Lieferorts",
        "BT-72": "Tatsächliches Lieferdatum",
        "BT-73": "Beginn des Rechnungszeitraums",
        "BT-74": "Ende des Rechnungszeitraums",
        "BT-75": "Lieferanschrift, Zeile 1",
        "BT-76": "Lieferanschrift, Zeile 2",
        "BT-77": "Ort der Lieferanschrift",
        "BT-78": "Postleitzahl der Lieferanschrift",
        "BT-79": "Region/Bundesland der Lieferanschrift",
        "BT-80": "Ländercode der Lieferanschrift",

        // --- Zahlung
        "BT-81": "Code für die Zahlungsart",
        "BT-82": "Text zur Zahlungsart",
        "BT-83": "Verwendungszweck",
        "BT-84": "Kennung des Zahlungskontos (z.B. IBAN)",
        "BT-85": "Name des Zahlungskontos",
        "BT-86": "Kennung des Zahlungsdienstleisters (z.B. BIC)",
        "BT-87": "Nummer der Zahlungskarte",
        "BT-88": "Name des Zahlungskarteninhabers",
        "BT-89": "Mandatsreferenz der Lastschrift",
        "BT-90": "Gläubiger-Identifikationsnummer",
        "BT-91": "Belastetes Konto (Lastschrift)",

        // --- Nachlässe/Zuschläge auf Dokumentenebene
        "BT-92": "Betrag des Nachlasses",
        "BT-93": "Basisbetrag des Nachlasses",
        "BT-94": "Prozentsatz des Nachlasses",
        "BT-95": "Umsatzsteuerkategorie des Nachlasses",
        "BT-96": "Umsatzsteuersatz des Nachlasses",
        "BT-97": "Grund des Nachlasses",
        "BT-98": "Code für den Nachlassgrund",
        "BT-99": "Betrag des Zuschlags",
        "BT-100": "Basisbetrag des Zuschlags",
        "BT-101": "Prozentsatz des Zuschlags",
        "BT-102": "Umsatzsteuerkategorie des Zuschlags",
        "BT-103": "Umsatzsteuersatz des Zuschlags",
        "BT-104": "Grund des Zuschlags",
        "BT-105": "Code für den Zuschlagsgrund",

        // --- Gesamtsummen
        "BT-106": "Summe der Nettobeträge aller Positionen",
        "BT-107": "Summe der Nachlässe auf Dokumentenebene",
        "BT-108": "Summe der Zuschläge auf Dokumentenebene",
        "BT-109": "Gesamtbetrag ohne Umsatzsteuer",
        "BT-110": "Gesamtbetrag der Umsatzsteuer",
        "BT-111": "Umsatzsteuergesamtbetrag in Abrechnungswährung",
        "BT-112": "Gesamtbetrag mit Umsatzsteuer",
        "BT-113": "Bereits gezahlter Betrag",
        "BT-114": "Rundungsbetrag",
        "BT-115": "Fälliger Zahlungsbetrag",

        // --- Umsatzsteueraufschlüsselung
        "BT-116": "Steuerbasisbetrag der Umsatzsteuerkategorie",
        "BT-117": "Steuerbetrag der Umsatzsteuerkategorie",
        "BT-118": "Code der Umsatzsteuerkategorie",
        "BT-119": "Umsatzsteuersatz der Kategorie",
        "BT-120": "Grund der Umsatzsteuerbefreiung",
        "BT-121": "Code für den Grund der Umsatzsteuerbefreiung",

        // --- Rechnungsbegründende Unterlagen
        "BT-122": "Kennung der rechnungsbegründenden Unterlage",
        "BT-123": "Beschreibung der Unterlage",
        "BT-124": "Externer Verweis auf die Unterlage",
        "BT-125": "Angehängtes Dokument",

        // --- Rechnungspositionen
        "BT-126": "Positionsnummer",
        "BT-127": "Anmerkung zur Position",
        "BT-128": "Kennung des Positionsgegenstands",
        "BT-129": "In Rechnung gestellte Menge",
        "BT-130": "Einheit der in Rechnung gestellten Menge",
        "BT-131": "Nettobetrag der Position",
        "BT-132": "Referenz zur Bestellposition",
        "BT-133": "Buchungsreferenz des Käufers zur Position",
        "BT-134": "Beginn des Rechnungszeitraums der Position",
        "BT-135": "Ende des Rechnungszeitraums der Position",
        "BT-136": "Betrag des Positionsnachlasses",
        "BT-137": "Basisbetrag des Positionsnachlasses",
        "BT-138": "Prozentsatz des Positionsnachlasses",
        "BT-139": "Grund des Positionsnachlasses",
        "BT-140": "Code für den Grund des Positionsnachlasses",
        "BT-141": "Betrag des Positionszuschlags",
        "BT-142": "Basisbetrag des Positionszuschlags",
        "BT-143": "Prozentsatz des Positionszuschlags",
        "BT-144": "Grund des Positionszuschlags",
        "BT-145": "Code für den Grund des Positionszuschlags",
        "BT-146": "Nettopreis des Artikels",
        "BT-147": "Nachlass auf den Artikelpreis",
        "BT-148": "Bruttopreis des Artikels",
        "BT-149": "Basismenge zum Artikelpreis",
        "BT-150": "Einheit der Preisbasismenge",
        "BT-151": "Code der Umsatzsteuerkategorie der Position",
        "BT-152": "Umsatzsteuersatz der Position",
        "BT-153": "Artikelname",
        "BT-154": "Artikelbeschreibung",
        "BT-155": "Artikelnummer des Verkäufers",
        "BT-156": "Artikelnummer des Käufers",
        "BT-157": "Standardartikelkennung (z.B. GTIN)",
        "BT-158": "Klassifikationskennung des Artikels",
        "BT-159": "Ursprungsland des Artikels",
        "BT-160": "Name des Artikelattributs",
        "BT-161": "Wert des Artikelattributs",

        // --- Zusatzzeilen der Anschriften (spät ergänzte Nummern)
        "BT-162": "Verkäuferanschrift, Zeile 3",
        "BT-163": "Käuferanschrift, Zeile 3",
        "BT-164": "Anschrift des Steuerbevollmächtigten, Zeile 3",
        "BT-165": "Lieferanschrift, Zeile 3",
    ]
}
